var json = {
    "channelType": {},
    "createdBy": {
        "id": 604252,
        "name": "Billy Bob"
    },
    "createdDate": "2012-08-24T9:42:34.803",
    "datasource": [
        {
            "id": 123,
            "type": "DE"
        },
        {
            "id": 456,
            "type": "list"
        }
    ],
    "description": "An example message",
    "encoding": "UTF-8",
    "id": "3e1e9869-2d9c-446c-bc99-d704ed40a1a8",
    "innerReference": "cd0e0a41-f158-4a72-8431-663263df3745",
    "isActive": true,
    "key": "ExampleMessage",
    "links": {
        "self": {
            "html": "http://www.etc.com/etc"
        }
    },
    "messageTemplate": {},
    "messageType": {},
    "modelType": "message",
    "modifiedBy": {
        "id": 821943,
        "name": "Billy Bob"
    },
    "modifiedDate": "2012-08-24T9:42:34.803",
    "name": "Example Message",
    "options": {},
    "source": "",
    "sourceGTL": "",
    "tags": [],
    "validated": true,
    "views": [
        {
            "content": "<div data-alias=\"master\" data-type=\"slot\"></div>",
            "createdBy": {
                "id": 604252,
                "name": "Billy Bob"
            },
            "createdDate": "2012-08-24T9:42:34.803",
            "description": "An example view",
            "devices": [],
            "generateFrom": "",
            "head": "",
            "id": "9fc692d5-cbe9-451d-ade4-829fd290620f",
            "innerReference": "0b1ea413-1b48-4dda-b6a7-9de64e179365",
            "isActive": true,
            "key": "ExampleView",
            "layout": {},
            "links": {
                "self": {
                    "html": "http://www.etc.com/etc"
                }
            },
            "modelType": "view",
            "modifiedBy": {
                "id": 821943,
                "name": "Billy Bob"
            },
            "modifiedDate": "2012-08-24T9:42:34.803",
            "name": "Example View",
            "options": {},
            "remodeling": {},
            "selections": {},
            "slots": [
                {
                    "alias": "master",
                    "allowed": [],
                    "altered": false,
                    "content": "<style type=\"text/css\">     a,     div,     li,     p,     td     {         -webkit-text-size-adjust: none     }      a {         color: #95becf;         text-decoration: none;     }      a:hover {         color: #6ca5bd;         text-decoration: underline;     }      body {         margin: 0;         padding: 0;     }      p {         margin: 0;         padding: 0;     }      .ReadMsgBody {         width: 100%     }      .ExternalClass {         width: 100%     } </style> <table style=\"color: #fff; line-height: normal; font-size: 14px; font-family: arial,helvetica,sans-serif;\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\"> <tbody> <tr>     <td bgcolor=\"#4a3729\" height=\"30\">         <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"620\">             <tbody>             <tr>                 <td width=\"10\">                 </td>                 <td width=\"600\">                     <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"600\">                         <tbody>                         <tr>                             <td style=\"font-family:Arial, helvetica, sans-serif; color:#ffffff; font-size:11px; line-height:14px;\" align=\"left\" height=\"30\" valign=\"middle\" width=\"350\">                                 <custom type=\"content\" name=\"cell1\"></custom>                             </td>                             <td style=\"font-family:Arial, helvetica, sans-serif; color:#ffffff; font-size:11px; line-height:14px;\" align=\"right\" height=\"30\" valign=\"middle\" width=\"250\">                                 Can't see the images? <a href=\"%%view_email_url%%\" target=\"_blank\" style=\"color:#ffffff;\" class=\"view_link\">View the Online Version</a>                             </td>                         </tr>                         </tbody>                     </table>                 </td>                 <td width=\"10\">                 </td>             </tr>             </tbody>         </table>     </td> </tr> <tr>     <td bgcolor=\"#37281c\">         <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"620\">             <tbody>             <tr>                 <td width=\"10\">                 </td>                 <td width=\"600\">                     <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"600\">                         <tbody>                         <tr>                             <td>                                 <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"600\">                                     <tbody>                                     <tr>                                         <td style=\"font-family:Arial, helvetica, sans-serif; color:#ffffff; font-size:20px; font-weight:bold;\" width=\"305\">                                             <img alt=\"Northern trail outfitters\" style=\"display: block; border: 0;\" src=\"http://image.s4.exct.net/lib/fe901570726d037d72/m/1/nto_logo_brown.jpg\" height=\"93\" width=\"305\">                                         </td>                                         <td valign=\"middle\">                                             <table style=\"margin-top: 6px; text-align: center; width: 100%;\">                                                 <tbody>                                                 <tr>                                                     <td style=\"background: #3b7992; border-bottom: 2px solid #255d74; border-right: 1px solid #255d74; color: #fffeff; font-size: 12px; font-weight: bold; padding: 8px 5px;\">                                                         <a href=\"#\" style=\"color: #fff;\" target=\"_blank\">MEN'S&nbsp;&nbsp;&gt;&gt;</a>                                                     </td>                                                     <td style=\"background: #3b7992; border-bottom: 2px solid #255d74; border-right: 1px solid #255d74; color: #fffeff; font-size: 12px; font-weight: bold; padding: 8px 5px;\">                                                         <a href=\"#\" style=\"color: #fff;\" target=\"_blank\">WOMEN'S&nbsp;&nbsp;&gt;&gt;</a>                                                     </td>                                                     <td style=\"background: #3b7992; border-bottom: 2px solid #255d74; border-right: 1px solid #255d74; color: #fffeff; font-size: 12px; font-weight: bold; padding: 8px 5px;\">                                                         <a href=\"#\" style=\"color: #fff;\" target=\"_blank\">KIDS'&nbsp;&nbsp;&gt;&gt;</a>                                                     </td>                                                     <td style=\"background: #3b7992; border-bottom: 2px solid #255d74; border-right: none; color: #fffeff; font-size: 12px; font-weight: bold; padding: 8px 5px;\">                                                         <a href=\"#\" style=\"color: #fff;\" target=\"_blank\">GEAR&nbsp;&nbsp;&gt;&gt;</a>                                                     </td>                                                 </tr>                                                 </tbody>                                             </table>                                         </td>                                     </tr>                                     </tbody>                                 </table>                             </td>                         </tr>                         <tr>                             <td>                                 <img src=\"http://internalcdn.xexacttargetapps.com/images/leaveNothingBehind.jpg\">                             </td>                         </tr>                         <tr>                             <td style=\"padding: 10px 0 0;\" valign=\"top\">                                 <table border=\"0\" width=\"600\">                                     <tbody>                                     <tr>                                         <td data-alias=\"midLeft\" data-type=\"slot\">                                         </td>                                         <td style=\"background: #37271a;\" width=\"2%\">                                         </td>                                         <td data-alias=\"midRight\" data-type=\"slot\">                                         </td>                                     </tr>                                     </tbody>                                 </table>                             </td>                         </tr>                         <tr>                             <td style=\"padding: 10px 0 0;\" valign=\"top\">                                 <table border=\"0\" width=\"600\">                                     <tbody>                                     <tr>                                         <td style=\"padding: 0; text-align: left;\" valign=\"top\" width=\"462\">                                             <img src=\"http://internalcdn.xexacttargetapps.com/images/registerNow.jpg\">                                         </td>                                         <td data-alias=\"registerRight\" data-type=\"slot\">                                         </td>                                     </tr>                                     </tbody>                                 </table>                             </td>                         </tr>                         <tr>                             <td valign=\"top\">                                 <div data-alias=\"A\" data-type=\"slot\">                                 </div>                             </td>                         </tr>                         <tr>                             <td valign=\"top\">                                 <div data-alias=\"B\" data-type=\"slot\">                                 </div>                             </td>                         </tr>                         </tbody>                     </table>                 </td>                 <td width=\"10\">                 </td>             </tr>             </tbody>         </table>     </td> </tr> <tr>     <td bgcolor=\"#4a3729\">         <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"620\">             <tbody>             <tr>                 <td width=\"10\">                 </td>                 <td width=\"600\">                     <table align=\"center\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"600\">                         <tbody>                         <tr>                             <td height=\"23\">                             </td>                         </tr>                         <tr>                             <td style=\"font-family:Arial, helvetica, sans-serif; color:#ffffff; font-size:12px; line-height:14px; font-weight:bold;\">                                 <a href=\"http://pages.s4.exacttarget.com/nto_contact\" target=\"_blank\" style=\"color:#ffffff;\">Contact Us</a> &nbsp;|&nbsp; <a href=\"%%profile_center_url%%\" target=\"_blank\" style=\"color:#ffffff;\">Profile Center</a> &nbsp;|&nbsp; <a href=\"http://pages.s4.exacttarget.com/nto_home\" target=\"_blank\" style=\"color:#ffffff;\">Store Locator</a> &nbsp;|&nbsp; <a href=\"%%unsub_center_url%%\" target=\"_blank\" style=\"color:#ffffff;\" title=\"Unsubscribe\">Unsubscribe</a> &nbsp;|&nbsp; <a href=\"http://pages.s4.exacttarget.com/nto_privacy\" target=\"_blank\" style=\"color:#ffffff;\">Privacy Policy</a> &nbsp;|&nbsp; <a href=\"http://pages.s4.exacttarget.com/nto_contact\" target=\"_blank\" style=\"color:#ffffff;\">Add to Address book</a>                             </td>                         </tr>                         <tr>                             <td height=\"26\">                             </td>                         </tr>                         <tr>                             <td>                                 <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"600\">                                     <tbody>                                     <tr>                                         <td style=\"font-family:Arial, helvetica, sans-serif; color:#ffffff; font-size:11px; line-height:14px;\" width=\"432\">                                             %%Member_Busname%% registered address: <br>                                             %%Member_Addr%% %%Member_City%%, %%Member_State%%, %%Member_PostalCode%%, %%Member_Country%%.<br>                                         </td>                                         <td valign=\"top\">                                             <table border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"168\">                                                 <tbody>                                                 <tr>                                                     <td width=\"35\">                                                         <a href=\"https://www.facebook.com/pages/Northern-Trail-Outfitters/142701739094034\" target=\"_blank\"><img alt=\"f\" style=\"display:block\" src=\"http://image.s4.exct.net/lib/fe901570726d037d72/m/1/facebook_icon.jpg\" border=\"0\" height=\"35\" width=\"35\"></a>                                                     </td>                                                     <td width=\"11\">                                                     </td>                                                     <td width=\"35\">                                                         <a href=\"https://twitter.com/NTOutfitters\" target=\"_blank\"><img alt=\"t\" style=\"display:block\" src=\"http://image.s4.exct.net/lib/fe901570726d037d72/m/1/twitter_icon.jpg\" border=\"0\" height=\"35\" width=\"35\"></a>                                                     </td>                                                     <td width=\"9\">                                                     </td>                                                     <td width=\"34\">                                                         <a href=\"http://pinterest.com/ntoutfitters/\" target=\"_blank\"><img alt=\"P\" style=\"display:block\" src=\"http://image.s4.exct.net/lib/fe901570726d037d72/m/1/pinterest_icon.jpg\" border=\"0\" height=\"35\" width=\"34\"></a>                                                     </td>                                                     <td width=\"9\">                                                     </td>                                                     <td width=\"35\">                                                         <a href=\"%%ftaf_url%%\" target=\"_blank\"><img alt=\"f2f\" style=\"display:block\" src=\"http://image.s4.exct.net/lib/fe901570726d037d72/m/1/forward_icon.jpg\" border=\"0\" height=\"35\" width=\"35\"></a>                                                     </td>                                                 </tr>                                                 </tbody>                                             </table>                                         </td>                                     </tr>                                     </tbody>                                 </table>                             </td>                         </tr>                         <tr>                             <td height=\"18\">                             </td>                         </tr>                         </tbody>                     </table>                 </td>                 <td width=\"10\">                 </td>             </tr>             </tbody>         </table>     </td> </tr> </tbody> </table> <div id=\"tracking_pixel\">     <custom name=\"opencounter\" type=\"tracking\"></custom> </div>",
                    "createdBy": {},
                    "createdDate": "",
                    "defaultContent": "",
                    "description": "",
                    "design": "",
                    "drop": [],
                    "element": "div",
                    "gears": [],
                    "groups": [],
                    "htmlAttributes": {
                        "class": "guide-master"
                    },
                    "id": "",
                    "innerReference": "",
                    "isActive": true,
                    "key": "",
                    "links": {},
                    "locked": false,
                    "maxGears": 999,
                    "minGears": 0,
                    "modelType": "slot",
                    "modifiedBy": {},
                    "modifiedDate": "",
                    "name": "",
                    "nesting": {
                        "gears": false,
                        "slots": true
                    },
                    "options": {},
                    "origin": "",
                    "restricted": [],
                    "slots": [
                        {
                            "alias": "midLeft",
                            "allowed": [],
                            "altered": true,
                            "content": "",
                            "createdBy": {},
                            "createdDate": "",
                            "defaultContent": "",
                            "description": "",
                            "design": "",
                            "drop": [],
                            "element": "div",
                            "gears": [],
                            "groups": [],
                            "htmlAttributes": {
                                "style": "background: #493627; height: 150px; padding: 5px; text-align: left;",
                                "valign": "top",
                                "width": "49%"
                            },
                            "id": "",
                            "innerReference": "",
                            "isActive": true,
                            "key": "",
                            "links": {},
                            "locked": false,
                            "maxGears": 999,
                            "minGears": 0,
                            "modelType": "slot",
                            "modifiedBy": {},
                            "modifiedDate": "",
                            "name": "",
                            "nesting": {
                                "gears": true,
                                "slots": false
                            },
                            "options": {},
                            "origin": "",
                            "restricted": [],
                            "slots": [],
                            "source": "",
                            "sourceGTL": "",
                            "tags": [],
                            "validated": false,
                            "version": ""
                        },
                        {
                            "alias": "midRight",
                            "allowed": [],
                            "altered": false,
                            "content": "",
                            "createdBy": {},
                            "createdDate": "",
                            "defaultContent": "",
                            "description": "",
                            "design": "",
                            "drop": [],
                            "element": "div",
                            "gears": [],
                            "groups": [],
                            "htmlAttributes": {
                                "style": "background: #493627; height: 150px; padding: 5px; text-align: left;",
                                "valign": "top",
                                "width": "49%"
                            },
                            "id": "",
                            "innerReference": "",
                            "isActive": true,
                            "key": "",
                            "links": {},
                            "locked": false,
                            "maxGears": 999,
                            "minGears": 0,
                            "modelType": "slot",
                            "modifiedBy": {},
                            "modifiedDate": "",
                            "name": "",
                            "nesting": {
                                "gears": true,
                                "slots": false
                            },
                            "options": {},
                            "origin": "",
                            "restricted": [],
                            "slots": [],
                            "source": "",
                            "sourceGTL": "",
                            "tags": [],
                            "validated": false,
                            "version": ""
                        },
                        {
                            "alias": "registerRight",
                            "allowed": [],
                            "altered": false,
                            "content": "",
                            "createdBy": {},
                            "createdDate": "",
                            "defaultContent": "<div style=\"cursor: pointer; display: block; font-size: 146px; color: #fff; font-weight: bold; text-align: center;\">&gt;</div>",
                            "description": "",
                            "design": "",
                            "drop": [],
                            "element": "div",
                            "gears": [],
                            "groups": [],
                            "htmlAttributes": {
                                "style": "background: #296679; border-radius: 0 6px 0 0; padding: 5px;",
                                "valign": "top"
                            },
                            "id": "",
                            "innerReference": "",
                            "isActive": true,
                            "key": "",
                            "links": {},
                            "locked": true,
                            "maxGears": 999,
                            "minGears": 0,
                            "modelType": "slot",
                            "modifiedBy": {},
                            "modifiedDate": "",
                            "name": "",
                            "nesting": {
                                "gears": true,
                                "slots": false
                            },
                            "options": {},
                            "origin": "",
                            "restricted": [],
                            "slots": [],
                            "source": "",
                            "sourceGTL": "",
                            "tags": [],
                            "validated": false,
                            "version": ""
                        },
                        {
                            "alias": "A",
                            "allowed": [],
                            "altered": false,
                            "content": "",
                            "createdBy": {},
                            "createdDate": "",
                            "defaultContent": "",
                            "description": "",
                            "design": "",
                            "drop": [],
                            "element": "div",
                            "gears": [],
                            "groups": [],
                            "htmlAttributes": {
                                "style": "background: #4a3728; margin: 10px 0 0; padding: 5px; min-height: 100px;"
                            },
                            "id": "",
                            "innerReference": "",
                            "isActive": true,
                            "key": "",
                            "links": {},
                            "locked": false,
                            "maxGears": 999,
                            "minGears": 0,
                            "modelType": "slot",
                            "modifiedBy": {},
                            "modifiedDate": "",
                            "name": "",
                            "nesting": {
                                "gears": true,
                                "slots": false
                            },
                            "options": {},
                            "origin": "",
                            "restricted": [],
                            "slots": [],
                            "source": "",
                            "sourceGTL": "",
                            "tags": [],
                            "validated": false,
                            "version": ""
                        },
                        {
                            "alias": "B",
                            "allowed": [],
                            "altered": false,
                            "content": "",
                            "createdBy": {},
                            "createdDate": "",
                            "defaultContent": "",
                            "description": "",
                            "design": "",
                            "drop": [],
                            "element": "div",
                            "gears": [],
                            "groups": [],
                            "htmlAttributes": {
                                "style": "background: #4a3728; margin: 10px 0; padding: 5px; min-height: 100px;"
                            },
                            "id": "",
                            "innerReference": "",
                            "isActive": true,
                            "key": "",
                            "links": {},
                            "locked": false,
                            "maxGears": 999,
                            "minGears": 0,
                            "modelType": "slot",
                            "modifiedBy": {},
                            "modifiedDate": "",
                            "name": "",
                            "nesting": {
                                "gears": true,
                                "slots": false
                            },
                            "options": {},
                            "origin": "",
                            "restricted": [],
                            "slots": [],
                            "source": "",
                            "sourceGTL": "",
                            "tags": [],
                            "validated": false,
                            "version": ""
                        }
                    ],
                    "source": "",
                    "sourceGTL": "",
                    "tags": [],
                    "validated": false,
                    "version": ""
                }
            ],
            "source": "",
            "sourceGTL": "",
            "theme": {},
            "version": "1.7.2",
            "viewTemplate": {},
            "viewType": {
                "createdBy": {},
                "createdDate": "",
                "description": "",
                "id": "",
                "innerReference": "",
                "isActive": true,
                "key": "",
                "kind": "emailhtmlbody",
                "links": {},
                "mimeType": "text/html",
                "modelType": "viewType",
                "modifiedBy": {},
                "modifiedDate": "",
                "name": "",
                "options": {},
                "source": "",
                "sourceGTL": "",
                "tags": [],
                "validated": false,
                "value": "text/html; kind=emailhtmlbody",
                "version": ""
            }
        },
        {
            "content": "Here's the text view",
            "createdBy": {
                "id": 604252,
                "name": "Billy Bob"
            },
            "createdDate": "2012-08-24T9:42:34.803",
            "description": "An example view",
            "devices": [],
            "generateFrom": "",
            "head": "",
            "id": "9605cd39-3da6-4938-a969-7fbf37caeca0",
            "innerReference": "50d3e3bd-041f-47b1-87b9-419c4ab64ff2",
            "isActive": true,
            "key": "ExampleView",
            "layout": {},
            "links": {
                "self": {
                    "html": "http://www.etc.com/etc"
                }
            },
            "modelType": "view",
            "modifiedBy": {
                "id": 821943,
                "name": "Billy Bob"
            },
            "modifiedDate": "2012-08-24T9:42:34.803",
            "name": "Example View",
            "options": {},
            "remodeling": {},
            "selections": {},
            "slots": [],
            "source": "",
            "sourceGTL": "",
            "theme": {},
            "version": "1.7.2",
            "viewTemplate": {},
            "viewType": {
                "createdBy": {},
                "createdDate": "",
                "description": "",
                "id": "",
                "innerReference": "",
                "isActive": true,
                "key": "",
                "kind": "emailtextbody",
                "links": {},
                "mimeType": "text/plain",
                "modelType": "viewType",
                "modifiedBy": {},
                "modifiedDate": "",
                "name": "",
                "options": {},
                "source": "",
                "sourceGTL": "",
                "tags": [],
                "validated": false,
                "value": "text/plain; kind=emailtextbody",
                "version": ""
            }
        },
        {
            "content": "Subject line",
            "createdBy": {
                "id": 604252,
                "name": "Billy Bob"
            },
            "createdDate": "2012-08-24T9:42:34.803",
            "description": "An example view",
            "devices": [],
            "generateFrom": "",
            "head": "",
            "id": "b2acd4ca-12e0-4701-97c2-d2d97de23f50",
            "innerReference": "50d3e3bd-041f-47b1-87b9-419c4ab64ff2",
            "isActive": true,
            "key": "ExampleView",
            "layout": {},
            "links": {
                "self": {
                    "html": "http://www.etc.com/etc"
                }
            },
            "modelType": "view",
            "modifiedBy": {
                "id": 821943,
                "name": "Billy Bob"
            },
            "modifiedDate": "2012-08-24T9:42:34.803",
            "name": "Example View",
            "options": {},
            "remodeling": {},
            "selections": {},
            "slots": [],
            "source": "",
            "sourceGTL": "",
            "theme": {},
            "version": "1.7.2",
            "viewTemplate": {},
            "viewType": {
                "createdBy": {},
                "createdDate": "",
                "description": "",
                "id": "",
                "innerReference": "",
                "isActive": true,
                "key": "",
                "kind": "subjectline",
                "links": {},
                "mimeType": "text/plain",
                "modelType": "viewType",
                "modifiedBy": {},
                "modifiedDate": "",
                "name": "",
                "options": {},
                "source": "",
                "sourceGTL": "",
                "tags": [],
                "validated": false,
                "value": "text/plain; kind=subjectline",
                "version": ""
            }
        }
    ],
    "version": "1.0.2"
}